#smartthings presentation:device-config:create --yaml --input deviceConfig.yaml
dashboard:
  states:
    - component: main
      capability: battery
      version: 1
      values: [ ]
      patch: [ ]
  actions:
    - component: main
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
detailView:
  - component: main
    capability: battery
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
  - component: button2
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
  - component: button3
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
  - component: button4
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button2
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button3
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button4
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
  actions:
    - component: main
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button2
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button3
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button4
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
type: dth
presentationId: ff3f5d4c-7b45-3b89-927e-710289f2b28d
manufacturerName: SmartThingsCommunity
vid: ff3f5d4c-7b45-3b89-927e-710289f2b28d
mnmn: SmartThingsCommunity
version: 0.0.1
