#smartthings presentation:device-config:create --yaml --input zigbee-tuya-button-3-presentation.yaml
mnmn: SmartThingsCommunity
vid: 329f0bbe-8564-3a7e-b102-d691ed51f8e2
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: battery
      version: 1
      idx: 0
      group: main
      values: []
  actions:
    - component: button1
      capability: button
      version: 1
      idx: 0
      group: main
detailView:
  - component: main
    capability: battery
    version: 1
  - component: button1
    capability: button
    version: 1
    values:
      - key: button.value
        enabledValues:
          - pushed
          - double
          - held
  - component: button2
    capability: button
    version: 1
    values:
      - key: button.value
        enabledValues:
          - pushed
          - double
          - held
  - component: button3
    capability: button
    version: 1
    values:
      - key: button.value
        enabledValues:
          - pushed
          - double
          - held
automation:
  conditions:
    - component: button1
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
    - component: button2
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
      exclusion: []
    - component: button3
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
  actions:
    - component: button1
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
    - component: button2
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
    - component: button3
      capability: button
      version: 1
      values:
        - key: button.value
          enabledValues:
            - pushed
            - double
            - held
presentationId: 329f0bbe-8564-3a7e-b102-d691ed51f8e2
manufacturerName: SmartThingsCommunity