#smartthings presentation:device-config:create --yaml --input zigbee-tuya-switch-2-presentation.yaml
mnmn: SmartThingsCommunity
vid: 4a68f156-37cd-35f0-926b-d1b7f092be12
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: battery
      version: 1
      idx: 0
      group: main
      values: [ ]
  actions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
detailView:
  - component: main
    capability: battery
    version: 1
    values: [ ]
    patch: [ ]
  - component: button1
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
  - component: button2
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button2
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
    - component: button2
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
presentationId: 4a68f156-37cd-35f0-926b-d1b7f092be12
manufacturerName: SmartThingsCommunity