#smartthings presentation:device-config:create --yaml --input zigbee-tuya-switch-3-presentation.yaml
mnmn: SmartThingsCommunity
vid: bc787364-1e72-3008-a815-af60d25cf1dd
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: battery
      version: 1
      idx: 0
      group: main
      values: []
  actions:
    - component: button1
      capability: button
      version: 1
      idx: 0
      group: main
detailView:
  - component: main
    capability: battery
    version: 1
    values: []
    patch: []
#    patch:
#      - op: replace
#        path: "/0/list/supportedValues"
#        value: supportedButtonValues.value
  - component: button1
    capability: button
    version: 1
    values: []
    patch: []
  - component: button2
    capability: button
    version: 1
    values: []
    patch: []
  - component: button3
    capability: button
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: button1
      capability: button
      version: 1
      values: []
      patch: []
    - component: button2
      capability: button
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: button3
      capability: button
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: button1
      capability: button
      version: 1
      values: []
      patch: []
    - component: button2
      capability: button
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: button3
      capability: button
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: bc787364-1e72-3008-a815-af60d25cf1dd
manufacturerName: SmartThingsCommunity